### ISSUE TITLE
.cinit only supports one dll

### ISSUE THREAD

**Issue by SimonRi1985** [tr8dr/.Net-Bridge#3]
Hi, 
currently one can only specify one dll-file in the `.cinit` function of the `rDotNet` package. This could easily be fixed by changing the internal `.initialize` function of the `rDotNet` package. 

First besides the inside functions `expand.dll` and `or` one had to specify a further function as: 
```
enlarge.dll <- function(dll) {
	server.args <- rep(NA, length(dll) * 2)
	for (i in 1:length(server.args)) {
		if (i%%2 == 1) {
			server.args[i] <- "-dll" 
		} else {
			server.args[i] <- dll[[i/2]]
		}
	}
	return(server.args)
}
```
And change the part where the arguments are sent to `CLRServer.exe` 

``` 
if (!is.null(dll))
   server.args <- c(server.args, "-dll", enlarge.dll(expand.dll(dll)))
else if (dll.env != "")
   server.args <- c(server.args, "-dll", expand.dll(dll.env))

```

Best Simon

**Comment by tr8dr** [comment]
Thanks, I can make this adjustment.   Since R somewhat faster avoiding loops (not that it matters much here for initialization), would change the enlarge.dll function above to:

```
enlarge.dll <- function(dll) {
    ndlls <- length(dll)
    server.args <- rep(NA, ndlls * 2)
    server.args[1:ndlls * 2 -1] <- "-dll"
    server.args[1:ndlls * 2] <- dll
    server.args
}
```
There is probably something ever more "clever" with apply and then a transform.    Feel free to do a fork and pull-request as / if you want to add features or fix bugs.

**Comment by tr8dr** [comment]
Before I commit this in, I noticed that your code does not use the expand.dll function.  Are you perhaps referring to dlls in the GAC as opposed to dlls referred to by path?   I recognize that expand.dll would not find any dll that is not path based (such as those in the GAC).   Curious as to how you use.   Thanks.

**Comment by tr8dr** [comment]
I've checked in the fixes and sent the new version to CRAN

**Comment by SimonRi1985** [comment]
Awesome! Thanks for the fast response Jonathan!
